apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  targetDefaultWorkgroupName: {{ .Values.configuration.targetDefaultWorkgroupName }}
  targetDefaultUserSub: {{ .Values.configuration.targetDefaultUserSub }}
  timezone: {{ .Values.app.timezone | default "Europe/Zurich" | quote }}
