apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: "true"
    keel.sh/trigger: poll
spec:
  schedule: "{{ .Values.app.schedule | default "0 0 * * *" }}"
  timeZone: "Europe/Zurich"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}
              image: ghcr.io/swisstopo/swissgeol-boreholes-suite-extern-sync:{{ .Values.app.version | default "latest" }}
              imagePullPolicy: Always
              env:
                - name: CONNECTIONSTRINGS__SourceBdmsContext
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secrets
                      key: sourceDatabaseConnectionString
                - name: CONNECTIONSTRINGS__TargetBdmsContext
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-secrets
                      key: targetDatabaseConnectionString
                - name: TARGET_DEFAULT_WORKGROUP_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: {{ .Release.Name }}-config
                      key: targetDefaultWorkgroupName
                - name: TARGET_DEFAULT_USER_SUB
                  valueFrom:
                    configMapKeyRef:
                      name: {{ .Release.Name }}-config
                      key: targetDefaultUserSub
                - name: TZ
                  valueFrom:
                    configMapKeyRef:
                      name: {{ .Release.Name }}-config
                      key: timezone
          restartPolicy: Never
      backoffLimit: 4
