apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  sourceDatabaseConnectionString: {{ printf "Host=%s:%s;Database=%s;Username=%s;Password=%s" .Values.db.source.host (default "5432" .Values.db.source.port) .Values.db.source.name .Values.db.source.username .Values.db.source.password | b64enc | quote }}
  targetDatabaseConnectionString: {{ printf "Host=%s:%s;Database=%s;Username=%s;Password=%s" .Values.db.target.host (default "5432" .Values.db.target.port) .Values.db.target.name .Values.db.target.username .Values.db.target.password | b64enc | quote }}
