# Default values for the swissgeol-boreholes application.
# This is a YAML-formatted file.

#
# General application configuration
#
app:
  # -- The fully qualified domain name the application gets accessed by
  # -- defaults to "boreholes.swissgeol.ch"
  domain:
  # -- The timezone which will be used in the application
  # -- defaults to "Europe/Zurich"
  timezone:
  # -- The tag name of the Docker image tag to be deployed
  # -- e.g. v2.0.506, latest or edge
  # -- defaults to "latest"
  version:

# OpenID Connect configuration
auth:
  # -- The issuer URL of the OpenID Connect provider
  # -- e.g. https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_XXXXXXXXX
  authority:
  # -- The client ID of the application
  audience:
  # -- The required scopes needed by the application
  # -- defaults to "openid profile"
  scopes:
  # -- The claim type to be used to get the user's groups
  # -- defaults to "cognito:groups"
  groupClaimType:
  # -- The name of the group the user must be a member of
  # -- defaults to "boreholes.swissgeol"
  authorizedGroupName:

# Database configuration
database:
  # -- The hostname of the database server
  host:
  # -- The port of the database server
  # -- defaults to "5432"
  port:
  # -- The name of the database
  name:
  # -- The username to connect to the database
  username:
  # -- The password to connect to the database
  password:

#
# Desired number of replicas for the application
#
replicaCount: 1

# AWS S3 Bucket configuration
s3:
  # -- The endpoint of the S3 bucket
  endpoint:
  # -- The name of the S3 bucket
  bucket:
  # -- The access key to connect to the S3 bucket
  accessKey:
  # -- The secret key to connect to the S3 bucket
  secretKey:
  # -- Set to 0 to use a insecure connection
  # -- defaults to 1 (secure connection)
  secure:
