apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  sourceDatabaseUsername: {{ default "" .Values.db.source.username | b64enc | quote }}
  sourceDatabasePassword: {{ default "" .Values.db.source.password | b64enc | quote }}
  targetDatabaseUsername: {{ default "" .Values.db.target.username | b64enc | quote }}
  targetDatabasePassword: {{ default "" .Values.db.target.password | b64enc | quote }}
