apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ocr-api
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.ocr.awsRoleArn | quote }}
