apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  databaseUsername: {{ default "" .Values.database.username | b64enc | quote }}
  databasePassword: {{ default "" .Values.database.password | b64enc | quote }}
  databaseConnectionString: {{ printf "Host=%s:%s;Database=%s;Username=%s;Password=%s" .Values.database.host (default "5432" .Values.database.port) .Values.database.name .Values.database.username .Values.database.password | b64enc | quote }}
  s3AccessKey: {{ default "" .Values.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ default "" .Values.s3.secretKey | b64enc | quote }}
